#!/usr/bin/env python3
"""Synchronize Chinese analysis docs with bilingual site chapters and frozen tables."""
from pathlib import Path
import re
from build_site import substitutions

ROOT=Path(__file__).resolve().parents[1]
mapping={'behavior':'behavior_analysis','optimization':'optimization_analysis','results':'experiment_report',
         'method':'proposal','protocol':'experiment_report','reproduce':'project_page'}
for source,target in [('behavior','behavior_analysis'),('optimization','optimization_analysis')]:
    text=(ROOT/f'site/chapters/{source}.zh.md').read_text(encoding='utf-8')
    for key,value in substitutions('zh').items():text=text.replace('{{'+key+'}}',value)
    text=text.replace('../figures/','../artifacts/analysis/figures/').replace('../data/','../artifacts/analysis/')
    for chapter,doc in mapping.items():text=text.replace('('+chapter+'.html','('+doc+'.md')
    text='<!-- Generated by scripts/render_analysis_docs.py from site/chapters and frozen analysis. -->\n\n'+text
    (ROOT/f'docs/{target}.md').write_text(text,encoding='utf-8')
print('Synchronized behavior and optimization analysis documents.')
